version: 1.0.{build}
skip_branch_with_pr: true
image:
  - Visual Studio 2017
  - ubuntu
install:
  - sh: sudo apt-get install -y libgtk-3-dev
  - git submodule update --init --recursive
build_script:
  - ps: .\ci_build.ps1
artifacts:
  - path: '**\*.nupkg'
